# Generated by Django 4.2.1 on 2023-10-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportSystem', '0003_alter_fraudreport_id_alter_reporthistory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudreport',
            name='assignedTime',
            field=models.DateTimeField(null=True),
        ),
    ]
